# Generated by Django 5.1.7 on 2025-03-25 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_notifications', '0007_note_instructor_alter_note_student'),
        ('users', '0003_alter_user_options_remove_instructor_signup_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.student'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
