# Generated by Django 5.1.7 on 2025-04-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_notifications', '0008_alter_note_student_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
