# Generated by Django 5.1.7 on 2025-04-08 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('st_notifications', '0009_note_read'),
        ('users', '0007_alter_track_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='users.track'),
        ),
    ]
