# Generated by Django 5.1.7 on 2025-04-15 08:01

import django.db.models.deletion
import labs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('file', models.FileField(upload_to=labs.models.lab_file_path)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_labs', to=settings.AUTH_USER_MODEL)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labs', to='users.track')),
            ],
        ),
    ]
