# Generated by Django 5.1.7 on 2025-04-10 23:49

import labs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='file',
            field=models.FileField(upload_to=labs.models.lab_file_path),
        ),
    ]
