# Generated by Django 5.1.7 on 2025-04-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='submission_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
