# Generated by Django 5.1.7 on 2025-05-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0002_lab_submission_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='file',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
