# Generated by Django 5.1.7 on 2025-04-22 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryexaminstance',
            name='instructor_id',
            field=models.ForeignKey(db_column='instructor_id', default=5, on_delete=django.db.models.deletion.CASCADE, to='users.instructor'),
        ),
        migrations.AlterField(
            model_name='cheatinglog',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codingquestion',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('xml', 'XML'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('razor', 'Razor'), ('markdown', 'Markdown'), ('yaml', 'YAML'), ('shell', 'Shell'), ('powershell', 'PowerShell'), ('lua', 'Lua'), ('r', 'R'), ('perl', 'Perl'), ('swift', 'Swift'), ('objective-c', 'Objective-C'), ('scss', 'SCSS'), ('less', 'LESS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('xml', 'XML'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('razor', 'Razor'), ('markdown', 'Markdown'), ('yaml', 'YAML'), ('shell', 'Shell'), ('powershell', 'PowerShell'), ('lua', 'Lua'), ('r', 'R'), ('perl', 'Perl'), ('swift', 'Swift'), ('objective-c', 'Objective-C'), ('scss', 'SCSS'), ('less', 'LESS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentexamanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='users.student'),
        ),
    ]
