# Generated by Django 5.1.7 on 2025-04-16 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_temporaryexaminstance_instructor'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporaryexaminstance',
            name='instructor',
        ),
        migrations.AddField(
            model_name='temporaryexaminstance',
            name='instructor_id',
            field=models.ForeignKey(blank=True, db_column='instructor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.instructor'),
        ),
        migrations.AlterField(
            model_name='cheatinglog',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
