# Generated by Django 5.1.7 on 2025-04-06 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
    ]
