# Generated by Django 5.1.7 on 2025-04-15 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_temporaryexaminstance_instructor'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporaryexaminstance',
            name='Instructor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to='users.instructor'),
            preserve_default=False,
        ),
    ]
