# Generated by Django 5.1.7 on 2025-04-20 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_temporaryexaminstance_instructor_and_more'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingquestion',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('xml', 'XML'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('razor', 'Razor'), ('markdown', 'Markdown'), ('yaml', 'YAML'), ('shell', 'Shell'), ('powershell', 'PowerShell'), ('lua', 'Lua'), ('r', 'R'), ('perl', 'Perl'), ('swift', 'Swift'), ('objective-c', 'Objective-C'), ('scss', 'SCSS'), ('less', 'LESS')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mcqquestion',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('typescript', 'TypeScript'), ('html', 'HTML'), ('css', 'CSS'), ('json', 'JSON'), ('xml', 'XML'), ('java', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('php', 'PHP'), ('razor', 'Razor'), ('markdown', 'Markdown'), ('yaml', 'YAML'), ('shell', 'Shell'), ('powershell', 'PowerShell'), ('lua', 'Lua'), ('r', 'R'), ('perl', 'Perl'), ('swift', 'Swift'), ('objective-c', 'Objective-C'), ('scss', 'SCSS'), ('less', 'LESS')], max_length=20),
        ),
     
        
    ]
