# Generated by Django 5.1.7 on 2025-04-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_cheatinglog'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingtestcase',
            name='function_name',
            field=models.CharField(blank=True, default='', help_text='Name of the function to test (leave blank for single-function questions)', max_length=100),
        ),
    ]
