# Generated by Django 5.1.7 on 2025-04-21 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_codingquestion_language_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexamanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='users.student'),
        ),
        migrations.AlterField(
            model_name='temporaryexaminstance',
            name='instructor_id',
            field=models.ForeignKey(db_column='instructor_id', on_delete=django.db.models.deletion.CASCADE, to='users.instructor'),
        ),
    ]
