# Generated by Django 5.1.7 on 2025-04-11 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_codingtestcase_function_name'),
        ('users', '0009_student_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='users.course'),
        ),
        migrations.AddField(
            model_name='temporaryexaminstance',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_instances', to='users.branch'),
        ),
    ]
