# Generated by Django 5.1.7 on 2025-03-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='signup_token',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
