# Generated by Django 5.1.7 on 2025-03-27 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='track',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='users.track'),
        ),
        migrations.AddField(
            model_name='track',
            name='instructors',
            field=models.ManyToManyField(related_name='tracks', to='users.instructor'),
        ),
    ]
