# Generated by Django 5.1.7 on 2025-03-27 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_track_instructor_remove_track_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='instructors',
        ),
        migrations.AddField(
            model_name='track',
            name='instructor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='track', to='users.instructor'),
        ),
    ]
