# Generated by Django 5.1.7 on 2025-04-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_track_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='leetcode_profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
