# Generated by Django 5.1.7 on 2025-04-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_leetcode_profile'),
        ('users', '0008_user_profile_image'),
        ('users', '0009_student_branch'),
    ]

    operations = [
    ]
