# Generated by Django 5.1.7 on 2025-04-12 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20250412_0154'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='users.branch'),
        ),
    ]
