# Generated by Django 5.1.7 on 2025-04-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_instructor_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='instructor',
        ),
        migrations.AddField(
            model_name='student',
            name='inrollment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='instructors',
            field=models.ManyToManyField(related_name='tracks', to='users.instructor'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
