# Generated by Django 5.1.7 on 2025-04-15 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_track_instructor_student_inrollment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='instructors',
        ),
        migrations.AddField(
            model_name='track',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='users.instructor'),
        ),
    ]
